### ISSUE TITLE
Error: Got error while parsing Fastfile

### ISSUE THREAD

**Issue by mfdeveloper** [smsimone/fastlane_launcher#4]
Hi there!

After install this extension and reload my vscode, the error below is always showing:

![ezgif-7-fecacf9a81](https://github.com/smsimone/fastlane_launcher/assets/431606/bb0bb8a4-6ae2-434a-b7ba-816104294a06)

Only this notification is displayed. I tried to see a detailed message error on vscode **_Output_** tab, but there isn't a pane for this extension there 😞 
 
I just did a simple `fastlane init` command, that generates the **Fastfile** below:

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
 desc "Runs all the tests"
 lane :test do
   gradle(task: "test")
 end

 desc "Submit a new Beta Build to Firebase App Distribution"
 lane :beta do
   gradle(task: "clean assembleRelease")
   firebase_app_distribution

   # sh "your_script.sh"
   # You can also use other beta testing services here
 end

 desc "Deploy a new version to Google Play"
 lane :deploy do
   gradle(task: "clean assembleRelease")
   upload_to_play_store
 end
end
```

**Comment by smsimone** [comment]
Hi! Are you on windows?

**Comment by mfdeveloper** [comment]
> Hi! Are you on windows?

@smsimone Yes, I am 😅

I'm using `fastlane` to automate builds for some **Android apps** and an **Unity game** as well. The game is cross-platform, and the PC version is mainly for Windows

**Comment by smsimone** [comment]
@mfdeveloper it was a problem given by how windows handles the paths

the version 0.1.2 which addresses this issue is now in verify, it will be soon available on the marketplace, thank you!

**Comment by mfdeveloper** [comment]
Hi @smsimone, thank you so much for your attention on this issue.

I tested right now, but unfortunately the error still persists 😢 
The downloaded version from marketplace is: `v0.2.0`. Is that actual fixed version?

![fastlane-launcher-version-resize](https://github.com/smsimone/fastlane_launcher/assets/431606/2b4dd1cf-44a1-4f03-b363-512809cf0d62)

Could you add an **_Output panel_** to this extension? Maybe that can help sharing my complete _stacktrace_ error with you :)
What do you think?

**Comment by smsimone** [comment]
Hi @mfdeveloper, I'm adding the output on the output panel right now, I hope to deliver it by tonight

**Comment by smsimone** [comment]
@mfdeveloper the new update should've been deployed on the store, can you check again?

**Comment by mfdeveloper** [comment]
@smsimone Sorry for my late response. I saw your message only right now.

 Follow my _stacktrace_ error below:

```bash
ℹ️: Found a single fastfile at path: file:///d%3A/projects/fastlane-project-test/fastlane/Fastfile
ℹ️: Made some magic on the path to make it windows like. New path: d:\projects\fastlane-project-test\fastlane\Fastfile
⛔️: Got error while creating tree view: Error: No lanes found
⛔️: Error: No lanes found
	at Object.parseFastfile (%HOME%\.vscode\extensions\smsimone.fastlane-launcher-0.2.1\out\parser.js:19:15)
	at populateView (%HOME%\.vscode\extensions\smsimone.fastlane-launcher-0.2.1\out\extension.js:191:27)
	at %HOME%\.vscode\extensions\smsimone.fastlane-launcher-0.2.1\out\extension.js:177:17
	at Generator.next (<anonymous>)
	at fulfilled (%HOME%\.vscode\extensions\smsimone.fastlane-launcher-0.2.1\out\extension.js:5:58)
```

Analyzing this error message, maybe you should replace the Windows backslash `\` by a simple slash `/`, right ?

By the way, what do you think to label the **_Output panel_** with the display name, like the others extensions?

![image](https://github.com/smsimone/fastlane_launcher/assets/431606/da5aaab5-e4f3-4c2d-bf3e-1083f5bbb060)

**Comment by smsimone** [comment]
> Analyzing this error message, maybe you should replace the Windows backslash \ by a simple slash /, right ?

Nope, on windows the right path is given by the backslashes, quite awful but that's it

Regarding the error `Error: No lanes found`, it's because right now the extensions looks for lines that starts with the regex `^(private_)?lane`, so the lane have to be put at the start of the line to be found. In your case, you're wrapping them in a `platform` section, which is indenting them inside by one tab

As a temporary workaround you could take them outside the platform section or align them on the left side 

> By the way, what do you think to label the Output panel with the display name, like the others extensions?

Yep, will do

**Comment by mfdeveloper** [comment]
Hi @smsimone !

I tried the both workarounds that you suggested, but I'm still seeing the error: `⛔️: Error: No lanes found` 😢 
Could you please try do that in your machine, with the `Fastfile` below?

```ruby

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "Runs all the tests"
lane :test do
  gradle(task: "test")
end

desc "Submit a new Beta Build to Firebase App Distribution"
lane :beta do
  gradle(task: "clean assembleRelease")
  firebase_app_distribution

  # sh "your_script.sh"
  # You can also use other beta testing services here
end

desc "Deploy a new version to Google Play"
lane :deploy do
  gradle(task: "clean assembleRelease")
  upload_to_play_store
end
```

**Comment by smsimone** [comment]
Hi @mfdeveloper! I've been busy with work and I managed to fix it now, as you update to version `0.2.2` it should be working

**Comment by mfdeveloper** [comment]
Hi @smsimone !

No problem! I understand you completely...I know what you mean with "busy with work" 😅 
Thanks a lot for your attention to solve that issue.

Yaaaay, now it works, even though using `platform` section !!! 🥳🎉 

![image](https://github.com/smsimone/fastlane_launcher/assets/431606/a36e0f0b-4a7a-412d-b519-55ab1951112e)

---

Additionally, I would like to suggest some extra changes:

- [ ] When click on lane, what do you think that **select/highlight** it instead of run ? Thus, you can add a context menu action to run and/or a keyboard shortcut.

- [ ] When runs a lane, could you prefix the `fastlane` command with **`bundle exec`** ? This is recommended on terminal output

  ```bash
  $ fastlane test
  [✔] 🚀 
  [16:19:54]: fastlane detected a Gemfile in the current directory
  [16:19:54]: However, it seems like you didn't use `bundle exec`
  [16:19:54]: To launch fastlane faster, please use
  [16:19:54]: 
  [16:19:54]: $ bundle exec fastlane test
  [16:19:54]: 
  [16:19:54]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
  ```

- [ ] Could you add meaningful icons for each kind of lane, like **Gitlens** extension does?
   > **e.g** lanes that starts or ends with `_test`, contains "`publish, deploy, alpha, beta...`" in lane name...
 
  ![image](https://github.com/smsimone/fastlane_launcher/assets/431606/1c0d16e2-fef0-4b9e-917f-aa8d28d136e9)

Maybe we can create one or more issues to implement each one of that suggestions. What do you think?

**Comment by smsimone** [comment]
If you could create an issue for each one would be nice! Anyway, regarding the second point, it's already implemented: you can write the command which will be called as you click on the lane in the settings

<img width="838" alt="image" src="https://github.com/smsimone/fastlane_launcher/assets/64575218/c914a9e1-32b8-4dac-b91d-8e2a7f3807dc">
